In [1]:
#Q.1:-Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method.
#Ans:- Method 1-
import numpy as np

# Method 1: Using numpy.array()
array1 = np.array([[1, 2, 3], [4, 5, 6]])

print("Array created using numpy.array():\n", array1)


Array created using numpy.array():
 [[1 2 3]
 [4 5 6]]


In [2]:
# Method 2:-
#Ans:-
# Method 2: Using numpy.zeros() and numpy.add()
array2 = np.zeros((2, 3))
array2 = np.add(array2, [[1, 2, 3], [4, 5, 6]])

print("\nArray created using numpy.zeros() and numpy.add():\n", array2)



Array created using numpy.zeros() and numpy.add():
 [[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
# Method 3: Using numpy.full()
array3 = np.full((2, 3), 0)
array3[0] = [1, 2, 3]
array3[1] = [4, 5, 6]

print("\nArray created using numpy.full():\n", array3)



Array created using numpy.full():
 [[1 2 3]
 [4 5 6]]


In [4]:
#Q.2:- Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that ID array into a 2D array.
#Ans:-
import numpy as np

# Step 1: Generate 100 evenly spaced numbers between 1 and 10
array_1d = np.linspace(1, 10, 100)

# Step 2: Reshape the 1D array into a 2D array with shape (10, 10)
array_2d = array_1d.reshape((10, 10))

print("1D Array of 100 evenly spaced numbers:\n", array_1d)
print("\nReshaped 2D Array (10x10):\n", array_2d)


1D Array of 100 evenly spaced numbers:
 [ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8

In [8]:
#Q.3:- Explain the following terms:

The difference in np.array, np.asarray and np.asanyarray. The difference between Deep copy and shallow copy.
#Ans:-
####    np.array:

This function creates a new NumPy array object, either from a sequence-like object (like lists or tuples) or from an existing array.
If the input is already a NumPy array, np.array will create a copy of the array by default unless copy=False is explicitly passed. This ensures that any changes made to the original array will not affect the newly created array.
 Example
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array(arr1)
arr2[0] = 99
print(arr1)  # [1, 2, 3] - arr1 is unchanged

##  np.asarray:

This function converts the input to a NumPy array, but if the input is already a NumPy array, it does not copy the array. Instead, it returns the original array.
This is useful when you want to ensure that the input is an array but avoid the overhead of copying data if it’s already an array.
Example:

arr1 = np.array([1, 2, 3])
arr2 = np.asarray(arr1)
arr2[0] = 99
print(arr1)  # [99, 2, 3] - arr1 is modified because arr2 is just a reference
 
###    np.asanyarray:

Similar to np.asarray, but with one key difference: if the input is a subclass of a NumPy array (like a masked array), it will not convert it to a base ndarray. Instead, it will return the subclass object itself.
This is useful when you want to maintain the type of the input array (e.g., if it’s a masked array) rather than converting it to a standard NumPy array.
Example:


arr1 = np.array([1, 2, 3])
arr2 = np.asanyarray(arr1)
print(type(arr2))  # <class 'numpy.ndarray'>
masked_arr = np.ma.array([1, 2, 3], mask=[0, 1, 0])
arr3 = np.asanyarray(masked_arr)
print(type(arr3))  # <class ''numpy.ma.core.MaskedArray'>
2. Difference Between Deep Copy and Shallow Copy

Shallow Copy:

A shallow copy of an object creates a new object, but does not create copies of nested objects within the original object. Instead, it copies references to the nested objects, so changes to the nested objects in the copy will also affect the original object.
In Python, this can be done using the copy() method or the copy module’s copy() function.
Example:

import copy
original = [[1, 2, 3], [4, 5, 6]]
shallow_copy = copy.copy(original)
shallow_copy[0][0] = 99
print(original)  # [[99, 2, 3], [4, 5, 6]] - original is modified


Deep Copy:

A deep copy of an object creates a new object, and recursively copies all objects nested within the original object. This means the copy is completely independent of the original, and changes to the copy do not affect the original.
In Python, this can be done using the copy module’s deepcopy() function.
Example:

import copy
original = [[1, 2, 3], [4, 5, 6]]
deep_copy = copy.deepcopy(original)
deep_copy[0][0] = 99
print(original)  # [[1, 2, 3], [4, 5, 6]] - original is unchanged

In [9]:
#Q.4:- Generate a 3x3 array with random floating-point numbers between 5 and 20. Then, round such number in the array to 2 decimal places.
#Ans:-
import numpy as np

# Generate a 3x3 array with random floats between 5 and 20
array = np.random.uniform(5, 20, size=(3, 3))

# Round each element in the array to 2 decimal places
rounded_array = np.round(array, 2)

print(rounded_array)


[[15.69 15.39  7.01]
 [ 7.74  8.16 14.35]
 [18.88 12.87 19.1 ]]


In [10]:
#Q.5:-Create a NumPy array with randorn integers between 1 and 10 of shape (5, 6). After creating the array perform the following operations

#a) Extract all even integers from array.

#b) Extract all add integers from array.
#Ans:-
import numpy as np

# Create a 5x6 array with random integers between 1 and 10
array = np.random.randint(1, 11, size=(5, 6))

# Extract all even integers from the array
even_integers = array[array % 2 == 0]

# Extract all odd integers from the array
odd_integers = array[array % 2 != 0]

print("Original Array:\n", array)
print("\nEven Integers:\n", even_integers)
print("\nOdd Integers:\n", odd_integers)


Original Array:
 [[ 5  3  3  2  7  7]
 [ 6  3  5  5  6  6]
 [ 1  5  4 10  7  6]
 [ 5  6  1  5  1  5]
 [ 4  4  7  5  2  6]]

Even Integers:
 [ 2  6  6  6  4 10  6  6  4  4  2  6]

Odd Integers:
 [5 3 3 7 7 3 5 5 1 5 7 5 1 5 1 5 7 5]


In [11]:
#Q.6:-6. Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the following operations:

#a) Find the indices of the maximum values along each depth level (third axis).

#b) Perform element-wise multiplication of between both array
#Ans:-
import numpy as np

# Create a 3D array of shape (3, 3, 3) with random integers between 1 and 10
array = np.random.randint(1, 11, size=(3, 3, 3))

# a) Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array, axis=2)

# b) Perform element-wise multiplication of the array with itself
multiplied_array = np.multiply(array, array)

print("Original 3D Array:\n", array)
print("\nIndices of maximum values along each depth level (axis=2):\n", max_indices)
print("\nElement-wise multiplication of the array with itself:\n", multiplied_array)


Original 3D Array:
 [[[ 3  5  8]
  [ 8  7  5]
  [ 3  3  9]]

 [[ 6  7  2]
  [10  5  5]
  [10  7 10]]

 [[ 5  7  1]
  [ 9  2  1]
  [ 6  4  5]]]

Indices of maximum values along each depth level (axis=2):
 [[2 0 2]
 [1 0 0]
 [1 0 0]]

Element-wise multiplication of the array with itself:
 [[[  9  25  64]
  [ 64  49  25]
  [  9   9  81]]

 [[ 36  49   4]
  [100  25  25]
  [100  49 100]]

 [[ 25  49   1]
  [ 81   4   1]
  [ 36  16  25]]]


In [2]:
#Q.7:- Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.
#Ans:-
import pandas as pd 
import numpy as np
df = pd.read_csv('People Data.csv')

def clean_phone(phone):
    if pd.isna(phone) or phone == '':
        return np.nan
  Remove non-numeric characters
    cleaned_phone = ''.join(filter(str.isdigit, phone))
     Return NaN if cleaned_phone is empty, otherwise return the cleaned phone number
    return np.nan if cleaned_phone == '' else int(cleaned_phone)

# Apply the cleaning function to the 'Phone' column
df['Phone'] = df['Phone'].apply(clean_phone)

# Convert the 'Phone' column to Int64 to handle integers with NaNs
df['Phone'] = df['Phone'].astype('Int64')

# Configure pandas to display numbers in full without scientific notation
pd.set_option('display.float_format', '{:.0f}'.format)

# Display the DataFrame and its data types
print("DATAFRAME : \n",df)
print("\nData Types :\n",df.dtypes)

In [ ]:
# 8.  Perform the following tasks using people dataset:

# a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

# b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

# c) Display the first 10 rows of the filtered dataset.

# d) Extract the ‘Salary’' column as a Series and display its last 5 values.


import pandas as pd 

df = pd.read_csv('People Data.csv', skiprows=50)

print("a) Dataframe after skipping first 50 rows : \n ",df)

In [ ]:
import pandas as pd


# b) Only read the columns: 'Last Name', 'Gender', 'Email', 'Phone', and 'Salary' from the file.
columns_to_read = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']
df_filtered = pd.read_csv('People Data.csv', usecols=columns_to_read)

# c) Display the first 10 rows of the filtered dataset.
print("c) First 10 rows of the filtered dataset:\n", df_filtered.head(10))

# d) Extract the ‘Salary’ column as a Series and display its last 5 values.
salary_series = df_filtered['Salary']
print("d) Last 5 values of the 'Salary' column:\n", salary_series.tail(5))

In [ ]:
# 9. Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and ‘Salary’ should be less than 85000.

import pandas as pd 
df = pd.read_csv('People Data.csv')

df[(df['Last Name'] =='Duke') & (df['Gender'] == 'Female') & (df['Salary'] < 85000) ]

In [ ]:
# 10.  Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6

import pandas as pd
import numpy as np

random_num = np.random.randint(1, 7, 35)
series = pd.Series(random_num)

df= pd.DataFrame(series.values.reshape(7,5))

print(df)

In [ ]:
# 11. Create two different Series, each of length 50, with the following criteria:

#a) The first Series should contain random numbers ranging from 10 to 50.

#b) The second Series should contain random numbers ranging from 100 to 1000.

#c) Create a DataFrame by joining these Series by column, and, change the names of the columns to 'col1', 'col2', etc


import pandas as pd
import numpy as np

random_n1 = np.random.randint(10, 51 , 50)
random_n2 = np.random.randint(100, 1001 , 50)

series_1 = pd.Series(random_n1)
series_2 = pd.Series(random_n2)

df = pd.concat([series_1, series_2] ,  axis=1)
df.columns =  ['col1' , 'col2'] 
print(df)

In [ ]:
#Q.12. Perform the following operations using people data set:

#a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

#b) Delete the rows containing any missing values.

#d) Print the final output also


import pandas as pd 

df = pd.read_csv('People Data.csv')

columns_to_del = ['Email' , 'Phone' , 'Date of birth' ]

# Drop the columns
df.drop(columns=columns_to_del , inplace=True)

# Drop rows with any missing values
df.dropna(inplace=True)
print(df.info())

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import seaborn as sns

In [ ]:
'''
Q.13. Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the following tasks using Matplotlib and NumPy:
a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.
b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.
c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.
d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.
e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.
f) Display a legend for the scatter plot, the horizontal line, and the vertical line
'''
x= np.random.rand(100)
y= np.random.rand(100)

plt.scatter(x,y ,color = 'red', marker = 'o')
plt.axhline(y=0.5, linestyle='--', label='y = 0.5')
plt.axvline(x=0.5, linestyle=':', label='x = 0.5')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Advanced Scatter Plot of Random Values')
plt.legend()
plt.show()

In [ ]:
'''
Q.14. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and Perform the following tasks using Matplotlib:
a) Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temperature' and right y-axis for 'Humidity').
b) Label the x-axis as 'Date'.
c) Set the title of the plot as 'Temperature and Humidity Over Time'.
'''
dates = pd.date_range('2023-01-01', periods=10)
df = pd.DataFrame({
    'Date': dates,
    'Temperature': [10, 12, 15, 18, 20, 22, 23, 21, 19, 17],
    'Humidity': [60, 65, 70, 75, 80, 85, 90, 88, 85, 80]
})


fig, ax1 = plt.subplots(figsize=(10, 6))

ax1.plot(df['Date'], df['Temperature'], color='b', label='Temperature')
ax1.set_ylabel('Temperature (°C)', color='b')

ax2 = ax1.twinx()
ax2.plot(df['Date'], df['Humidity'], color='g', label='Humidity')
ax2.set_ylabel('Humidity (%)', color='g')

ax1.set_xlabel('Date')
ax1.set_title('Temperature and Humidity Over Time')

plt.legend(loc='upper left')
plt.grid(True)

plt.show()

In [ ]:
'''
Q.15. Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following
tasks using Matplotlib:
a) Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temerature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the plot as 'Temperature and Humidity Over Time'.

'''

data = np.random.normal(loc=0, scale=1, size=1000)

plt.figure(figsize=(10, 6))
plt.hist(data, bins=30, density=True, edgecolor='black')

x = np.linspace(-4, 4, 1000)
y = (1 / (np.sqrt(2 * np.pi))) * np.exp(-(x**2) / 2)
plt.plot(x, y, linewidth=2, color='red')

plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')

plt.show()

In [ ]:
# 16. Set the title of the plot as 'Histogram with PDF Overlay'.
plt.title('Histogram with PDF Overlay')


In [ ]:
# 17. Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the
#origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.
x = np.random.rand(100)
y = np.random.rand(100)

sns.scatterplot(x=x, y=y, hue=(x > 0) & (y > 0))

plt.legend(title='Quadrant', labels=['Quadrant I', 'Other Quadrants'])

plt.xlabel('X Axis')
plt.ylabel('Y Axis')

plt.title('Scatter Plot with Quadrant Coloring')

plt.show()

In [ ]:
#18. With Bokeh, plot a line chart of a sine wave function, add grid lines, label the axes, and set the title as 'Sine
#Wave Function'

from bokeh.plotting import figure, show

x = list(range(100))

y = [np.sin(i) for i in x]

p = figure(title="Sine Wave Function", y_range=(-1.1, 1.1))

p.line(x, y, line_width=2)

p.grid.grid_line_color = None

show(p)

In [ ]:
#19. Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical Bar Chart'

from bokeh.plotting import figure, show
from bokeh.palettes import Spectral8

data = {
    "categories": list("ABCDEFGH"),
    "values": np.random.randint(low=1, high=100, size=8),
    "colors": Spectral8
}

p = figure(title="Bar Chart", y_range=(0, data["values"].max() + 10))

p.vbar(x="categories", top="values", width=0.5, color="colors", source=data)

show(p)

In [ ]:
#20. Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as 'Simple Line Plot'

import plotly.graph_objects as go

x = list(range(100))
y = [np.random.randint(1, 100) for _ in range(100)]

fig = go.Figure(data=go.Scatter(x=x, y=y, mode='lines'))

fig.update_layout(
    title="Simple Line Plot",
    xaxis_title="X Axis",
    yaxis_title="Y Axis",
)

fig.show()

In [ ]:
# 21. Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentates, set the title as 'Interactive Pie Chart'.
import plotly.graph_objects as go


labels = ["Category 1", "Category 2", "Category 3", "Category 4"]
values = [np.random.randint(1, 100) for _ in range(4)]


fig = go.Figure(data=[go.Pie(labels=labels, values=values)])


fig.update_layout(
    title="Interactive Pie Chart",
    showlegend=False,
)

fig.update_traces(textinfo="label+percent", textposition="inside")

fig.show()
